/**
 * Placeholder client reviews for PS Viswanathan Advocate.
 * Replace with real testimonials before production launch.
 */

export const REVIEWS = [
  { name: "Priya Sharma", tag: "Family", rating: 5, text: "Mr. Viswanathan handled my divorce proceedings with great sensitivity and professionalism. He explained every step clearly and secured a fair settlement." },
  { name: "Rajesh Kumar", tag: "Consumer", rating: 5, text: "I had a defective product dispute with a major retailer. He filed the consumer complaint and we won compensation within three months." },
  { name: "Anitha Reddy", tag: "Civil", rating: 5, text: "Outstanding civil litigation support. His analytical approach from his IT background really showed in how he prepared our case documents." },
  { name: "Suresh Nair", tag: "Property", rating: 5, text: "Got a thorough legal opinion on a BTM Layout property purchase. His title verification saved us from a problematic deal." },
  { name: "Meera Iyer", tag: "Cheque Bounce", rating: 5, text: "Recovered my dues through a Section 138 case efficiently. Clear communication throughout and realistic expectations set from day one." },
  { name: "Vikram Patel", tag: "Arbitration", rating: 5, text: "Our commercial dispute was resolved through arbitration much faster than court. Excellent drafting of the arbitration petition." },
  { name: "Lakshmi Devi", tag: "Family", rating: 5, text: "Handled my child custody matter with compassion. Always available for calls and kept me informed at every hearing." },
  { name: "Arun Menon", tag: "Consumer", rating: 4, text: "Good experience with a banking service complaint. Professional and responsive, though the forum process took longer than expected." },
  { name: "Deepa Krishnan", tag: "Civil", rating: 5, text: "Represented us in a breach of contract case. His attention to detail in evidence compilation was impressive." },
  { name: "Karthik Rao", tag: "Property", rating: 5, text: "Registration and conveyancing done smoothly for our apartment. All documents verified and explained in plain language." },
  { name: "Sunita Agarwal", tag: "Family", rating: 5, text: "Mutual consent divorce completed without unnecessary delays. Fees were transparent and reasonable." },
  { name: "Mohammed Ali", tag: "Cheque Bounce", rating: 5, text: "Business payment dispute resolved favourably. He knew exactly which legal notices to send and when." },
  { name: "Ramesh Babu", tag: "Arbitration", rating: 4, text: "Solid arbitration counsel for a partnership dispute. Would have appreciated slightly faster document turnaround." },
  { name: "Nandini Gowda", tag: "Consumer", rating: 5, text: "Won my case against an insurance company that denied rightful claims. Highly recommend for consumer matters." },
  { name: "Harish Chandra", tag: "Civil", rating: 5, text: "Defended us in a property boundary dispute. Court appreciated the well-prepared maps and title documents." },
  { name: "Pooja Sinha", tag: "Property", rating: 5, text: "Legal opinion on ancestral property division was comprehensive. Family members finally had clarity on shares." },
  { name: "Ganesh Murthy", tag: "Family", rating: 5, text: "Alimony and maintenance case handled expertly. Fair outcome achieved for my client referral." },
  { name: "Shalini Verma", tag: "Arbitration", rating: 5, text: "Construction contract arbitration led to a settlement we were happy with. Strategic and pragmatic advice." },
  { name: "Ravi Shankar", tag: "Cheque Bounce", rating: 5, text: "Quick action on dishonoured cheque from a vendor. Settlement reached before trial." },
  { name: "Kavitha N", tag: "Consumer", rating: 5, text: "Educational institution fee refund case won. He understood consumer law nuances very well." },
  { name: "Sanjay Hegde", tag: "Civil", rating: 4, text: "Injunction matter handled competently. Good courtroom presence and clear legal strategy." },
  { name: "Divya Rangan", tag: "Property", rating: 5, text: "Khata transfer and registration guidance was invaluable for our new home in Bengaluru." },
  { name: "Manoj Tiwari", tag: "Family", rating: 5, text: "Domestic violence protection order obtained swiftly. Supportive and decisive when it mattered most." },
  { name: "Asha Pillai", tag: "Arbitration", rating: 5, text: "Employment arbitration for wrongful termination. Settlement exceeded our initial expectations." },
  { name: "Naveen Joshi", tag: "Cheque Bounce", rating: 4, text: "Professional handling of a bounced cheque from a tenant. Case is progressing well." },
  { name: "Rekha Bhat", tag: "Consumer", rating: 5, text: "Builder delay complaint at consumer forum. Partial refund and compensation awarded." },
  { name: "Prakash Shetty", tag: "Civil", rating: 5, text: "Suit for recovery of dues filed and decreed. Efficient follow-through on execution proceedings." },
  { name: "Uma Krishnamurthy", tag: "Property", rating: 5, text: "Joint development agreement review caught several risky clauses. Negotiated better terms." },
  { name: "Farhan Khan", tag: "Family", rating: 5, text: "Restitution of conjugal rights and subsequent mediation handled with cultural sensitivity." },
  { name: "Bhavana Desai", tag: "Arbitration", rating: 5, text: "Franchise dispute arbitration — clear-headed advice and strong written submissions." },
  { name: "Chetan Malhotra", tag: "Cheque Bounce", rating: 5, text: "Two cheque bounce cases consolidated and resolved. Saved time and legal costs." },
  { name: "Indira Rao", tag: "Consumer", rating: 4, text: "Telecom billing dispute resolved. Good communicator who simplifies complex legal terms." },
  { name: "Venkat Subramanian", tag: "Civil", rating: 5, text: "Specific performance suit for property sale agreement. Decree in our favour." },
  { name: "Swathi M", tag: "Property", rating: 5, text: "Encumbrance certificate analysis and sale deed drafting done meticulously." },
  { name: "Rohit Agarwal", tag: "Family", rating: 5, text: "Guardianship petition for minor child approved. Very thorough with documentation." },
  { name: "Lalitha Menon", tag: "Arbitration", rating: 4, text: "Supply chain contract dispute referred to arbitration. Fair arbitrator selection advice." },
  { name: "Ajay Reddy", tag: "Cheque Bounce", rating: 5, text: "Recovered full principal plus interest through NI Act proceedings." },
  { name: "Geetha Nambiar", tag: "Consumer", rating: 5, text: "Medical negligence consumer complaint — referred to appropriate forum with strong drafting." },
  { name: "Srinivas Murthy", tag: "Civil", rating: 5, text: "Partition suit among siblings settled through mediation he facilitated." },
  { name: "Tanvi Shah", tag: "Property", rating: 5, text: "Gift deed registration and stamp duty guidance saved us from future disputes." },
  { name: "Kiran Poojary", tag: "Family", rating: 4, text: "Judicial separation petition filed and granted. Process was smoother than anticipated." },
  { name: "Nitin Bansal", tag: "Arbitration", rating: 5, text: "IT services contract arbitration — his tech background helped explain technical clauses to the tribunal." },
  { name: "Padma Srinivasan", tag: "Cheque Bounce", rating: 5, text: "Prompt legal notice and criminal complaint filing. Defaulter agreed to pay within weeks." },
  { name: "Varun Khanna", tag: "Consumer", rating: 5, text: "E-commerce fraud refund obtained. Knew exactly how to frame the deficiency of service." },
  { name: "Madhavi L", tag: "Civil", rating: 5, text: "Defamation suit advice was pragmatic — chose civil remedy that achieved our goal." },
  { name: "Arjun Das", tag: "Property", rating: 4, text: "Layout legality opinion for BTM property. Detailed report with risk assessment." },
  { name: "Sneha Kapoor", tag: "Family", rating: 5, text: "Domestic violence and divorce combined strategy worked well. Felt supported throughout." },
  { name: "Hariprasad V", tag: "Arbitration", rating: 5, text: "Real estate joint venture arbitration concluded with property rights clarified." },
  { name: "Jyoti Mehta", tag: "Cheque Bounce", rating: 5, text: "Handled multiple bounced cheques from a single debtor efficiently." },
  { name: "Balaji S", tag: "Consumer", rating: 5, text: "Car dealership warranty denial overturned at district forum." },
  { name: "Ritu Chawla", tag: "Civil", rating: 5, text: "Eviction suit for commercial premises — decree and possession obtained." },
  { name: "Dinesh Kulkarni", tag: "Property", rating: 5, text: "Conversion and mutation guidance for agricultural land sale." },
  { name: "Anjali Thomas", tag: "Family", rating: 5, text: "Interim maintenance order secured within first two hearings." },
  { name: "Siddharth Jain", tag: "Arbitration", rating: 4, text: "Shareholders agreement dispute — arbitration clause enforced successfully." },
  { name: "Malini R", tag: "Cheque Bounce", rating: 5, text: "Clear timeline provided for NI Act case from notice to trial." },
  { name: "Gopalakrishnan", tag: "Consumer", rating: 5, text: "Housing society maintenance overcharge complaint resolved." },
  { name: "Neha Dutta", tag: "Civil", rating: 5, text: "Money suit for unpaid invoices — summary judgment obtained." },
  { name: "Vishal Oberoi", tag: "Property", rating: 5, text: "Lease agreement drafting and registration for commercial space." },
  { name: "Shweta B", tag: "Family", rating: 5, text: "Child visitation rights negotiated amicably after separation." },
  { name: "Pradeep N", tag: "Arbitration", rating: 5, text: "Logistics contract arbitration — award enforced without further litigation." },
  { name: "Kamala S", tag: "Cheque Bounce", rating: 4, text: "Compounding of offence negotiated after settlement. Practical approach." },
  { name: "Abhishek Roy", tag: "Consumer", rating: 5, text: "Travel agency package fraud — full refund plus compensation." },
  { name: "Latha Raman", tag: "Civil", rating: 5, text: "Permanent injunction against illegal construction granted." },
  { name: "Imran Shaikh", tag: "Property", rating: 5, text: "Power of attorney verification before property transaction — essential due diligence." },
  { name: "Chitralekha", tag: "Family", rating: 5, text: "Domestic violence case and divorce parallel track managed efficiently." },
  { name: "Raghunandan", tag: "Arbitration", rating: 5, text: "Media content licensing dispute arbitrated with favourable terms." },
  { name: "Pallavi G", tag: "Cheque Bounce", rating: 5, text: "Secured conviction and compensation in cheque dishonour matter." },
  { name: "Sunil Choudhary", tag: "Consumer", rating: 4, text: "Furniture quality complaint — replacement ordered by forum." },
  { name: "Meenakshi", tag: "Civil", rating: 5, text: "Suit for declaration of title succeeded. Property records now clean." },
  { name: "Tarun Mehra", tag: "Property", rating: 5, text: "RERA-related property opinion helped us choose the right project." },
  { name: "Radha Krishnan", tag: "Family", rating: 5, text: "Mutual consent divorce with child custody arrangement documented clearly." },
  { name: "Nikhil S", tag: "Arbitration", rating: 5, text: "Software licensing arbitration — unique advantage given his IT experience." },
  { name: "Savitha", tag: "Cheque Bounce", rating: 5, text: "Friend's referral — recovered loan amount via cheque bounce case." },
  { name: "Gaurav Mittal", tag: "Consumer", rating: 5, text: "Credit card wrongful charge dispute resolved at banking ombudsman level." },
  { name: "Hema V", tag: "Civil", rating: 4, text: "Partnership dissolution suit — fair settlement before final judgment." },
  { name: "Joseph Mathew", tag: "Property", rating: 5, text: "Will and succession planning for family property documented properly." },
  { name: "Aishwarya", tag: "Family", rating: 5, text: "Restraining order and divorce filed together — felt protected throughout." },
  { name: "Bharath Kumar", tag: "Arbitration", rating: 5, text: "Vendor payment arbitration in IT procurement — domain expertise evident." },
  { name: "Sujatha", tag: "Cheque Bounce", rating: 5, text: "Legal notice drafted perfectly — debtor paid before court date." },
  { name: "Rahul Saxena", tag: "Consumer", rating: 5, text: "Home appliance warranty claim enforced through consumer forum." },
  { name: "Mangala", tag: "Civil", rating: 5, text: "Mesne profits claim for unauthorised property use — decree obtained." },
  { name: "Faisal Ahmed", tag: "Property", rating: 5, text: "Commercial lease registration and stamp duty calculation accurate." },
  { name: "Preethi", tag: "Family", rating: 4, text: "Alimony revision petition successful. Responsive to urgent queries." },
  { name: "Devendra", tag: "Arbitration", rating: 5, text: "Construction delay arbitration — damages awarded as claimed." },
  { name: "Anuradha", tag: "Cheque Bounce", rating: 5, text: "Multiple cheque cases against same party consolidated smartly." },
  { name: "Karthik", tag: "Consumer", rating: 5, text: "Online course refund dispute — deficiency in service proved." },
  { name: "Shobha", tag: "Civil", rating: 5, text: "Suit for mandatory injunction to remove encroachment — successful." },
  { name: "Manish Gupta", tag: "Property", rating: 5, text: "Due diligence for plot purchase in Bengaluru outskirts — thorough report." },
  { name: "Revathi", tag: "Family", rating: 5, text: "Grandparents visitation rights petition — sensitive handling appreciated." },
  { name: "Sandeep", tag: "Arbitration", rating: 4, text: "Distribution agreement dispute — arbitration award in our favour." },
  { name: "Yamini", tag: "Cheque Bounce", rating: 5, text: "Explained NI Act procedure clearly. Settlement at Lok Adalat." },
  { name: "Aravind", tag: "Consumer", rating: 5, text: "Hospital billing overcharge complaint — partial refund received." },
  { name: "Lakshmi", tag: "Civil", rating: 5, text: "Appeal in civil suit — grounds well argued, order modified favourably." },
  { name: "Nitin", tag: "Property", rating: 5, text: "Family partition deed registered without disputes among heirs." },
  { name: "Padmini", tag: "Family", rating: 5, text: "NRI divorce matter coordinated with court appearances — seamless." },
  { name: "Vivek", tag: "Arbitration", rating: 5, text: "Consulting contract arbitration resolved within six months." },
  { name: "Gayathri", tag: "Cheque Bounce", rating: 5, text: "Business partner cheque dishonour — full recovery with interest." },
  { name: "Rohit", tag: "Consumer", rating: 4, text: "Gym membership refund case — fair outcome at district forum." },
  { name: "Saranya", tag: "Civil", rating: 5, text: "Specific relief act application for cancelled agreement — granted." },
  { name: "Aditya", tag: "Property", rating: 5, text: "Builder-buyer agreement review before signing — several red flags removed." },
  { name: "Kamini", tag: "Family", rating: 5, text: "Domestic violence and maintenance — both reliefs obtained." },
  { name: "Pranav", tag: "Arbitration", rating: 5, text: "Technology licensing arbitration — technical clauses explained to panel." },
  { name: "Bhavya", tag: "Cheque Bounce", rating: 5, text: "Vendor payment recovery through Section 138 — highly effective." },
  { name: "Omkar", tag: "Consumer", rating: 5, text: "Defective electronics refund plus compensation from major brand." },
  { name: "Nalini", tag: "Civil", rating: 5, text: "Suit for recovery of possession and mesne profits — comprehensive victory." },
  { name: "Harsha", tag: "Property", rating: 5, text: "Legal scrutiny of sale deed before registration — peace of mind." },
  { name: "Tejas", tag: "Family", rating: 5, text: "Child custody and visitation — child's welfare prioritised in arguments." },
  { name: "Ananya", tag: "Arbitration", rating: 5, text: "Partnership dissolution arbitration — assets divided fairly per award." },
  { name: "Murali", tag: "Cheque Bounce", rating: 4, text: "Cheque bounce case ongoing — excellent preparation so far." },
  { name: "Keerthi", tag: "Consumer", rating: 5, text: "Misleading advertisement complaint — corrective action ordered." },
  { name: "Sachin", tag: "Civil", rating: 5, text: "Declaratory suit for easement rights — decree in favour." },
  { name: "Divyashree", tag: "Property", rating: 5, text: "Conveyance deed execution and registration completed hassle-free." },
  { name: "Raghav", tag: "Family", rating: 5, text: "Mutual consent divorce for NRI couple — video testimony arranged." },
  { name: "Shanti", tag: "Arbitration", rating: 5, text: "Family business arbitration — preserved relationships while settling disputes." },
  { name: "Varsha", tag: "Cheque Bounce", rating: 5, text: "Loan repayment via dishonoured cheques — criminal and civil tracks explained." },
  { name: "Girish", tag: "Consumer", rating: 5, text: "Water purifier false claim case — replacement and damages awarded." },
  { name: "Aparna", tag: "Civil", rating: 5, text: "Breach of confidentiality suit — interim injunction granted immediately." },
  { name: "Naveen", tag: "Property", rating: 5, text: "BTM Layout flat purchase legal opinion — encumbrance free confirmed." },
  { name: "Sowmya", tag: "Family", rating: 5, text: "Maintenance for elderly parent — order passed in first month." },
  { name: "Rakesh", tag: "Arbitration", rating: 5, text: "Sub-contractor payment arbitration — award enforced successfully." },
  { name: "Leela", tag: "Cheque Bounce", rating: 5, text: "Recovered business dues without lengthy trial — skilled negotiator." },
  { name: "Ashok", tag: "Consumer", rating: 4, text: "Insurance claim rejection overturned — partial settlement received." },
  { name: "Priyanka", tag: "Civil", rating: 5, text: "Suit for cancellation of fraudulent sale deed — decree obtained." },
  { name: "Venugopal", tag: "Property", rating: 5, text: "Rectification deed drafted and registered to correct title error." },
  { name: "Mythili", tag: "Family", rating: 5, text: "Domestic violence case — protection order and separate residence secured." },
  { name: "Surya", tag: "Arbitration", rating: 5, text: "Joint venture arbitration — exit terms enforced per agreement." },
  { name: "Kavita", tag: "Cheque Bounce", rating: 5, text: "Section 138 case from start to finish — professional and persistent." },
  { name: "Harish", tag: "Consumer", rating: 5, text: "Builder possession delay — compensation and interest awarded." },
  { name: "Ramya", tag: "Civil", rating: 5, text: "Injunction against trademark infringement — quick relief obtained." },
  { name: "Dhanush", tag: "Property", rating: 5, text: "Agricultural land conversion opinion before purchase — wise counsel." },
  { name: "Usha", tag: "Family", rating: 5, text: "Divorce and property settlement negotiated in single mediation session." },
  { name: "Vijay", tag: "Arbitration", rating: 4, text: "Commercial lease dispute arbitration — reasonable settlement reached." },
  { name: "Shilpa", tag: "Cheque Bounce", rating: 5, text: "Friend referred me — cheque bounce recovery was faster than expected." },
  { name: "Ganesh", tag: "Consumer", rating: 5, text: "Defective construction material complaint — builder directed to rectify." },
  { name: "Nirmala", tag: "Civil", rating: 5, text: "Suit for specific performance of agreement to sell — decree passed." },
  { name: "Arun", tag: "Property", rating: 5, text: "End-to-end registration support for residential plot in Bengaluru." },
  { name: "Deepika", tag: "Family", rating: 5, text: "Compassionate advocate for women's rights in matrimonial disputes." },
  { name: "Santosh", tag: "Arbitration", rating: 5, text: "Procurement contract arbitration — saved our company significant litigation costs." },
  { name: "Lalitha", tag: "Cheque Bounce", rating: 5, text: "Dishonoured post-dated cheques — conviction and compensation ordered." },
  { name: "Prakash", tag: "Consumer", rating: 5, text: "Mis-sold financial product complaint — refund with interest." },
  { name: "Megha", tag: "Civil", rating: 5, text: "Recovery suit with attachment of property — decree executed fully." },
  { name: "Rajan", tag: "Property", rating: 5, text: "Title search and legal opinion before bank loan — lender approved quickly." },
  { name: "Swetha", tag: "Family", rating: 5, text: "Handled complex NRI divorce with property in India and abroad." },
  { name: "Kumar", tag: "Arbitration", rating: 5, text: "Service agreement arbitration — termination clause interpreted favourably." },
  { name: "Anita", tag: "Cheque Bounce", rating: 5, text: "Business loan security cheque bounced — full amount recovered." },
  { name: "Rohini", tag: "Consumer", rating: 5, text: "False product labelling case — manufacturer penalised." },
  { name: "Suresh", tag: "Civil", rating: 4, text: "Civil appeal drafting was thorough. Awaiting final hearing." },
  { name: "Pooja", tag: "Property", rating: 5, text: "Sale agreement vetting prevented unfavourable payment terms." },
  { name: "Mahesh", tag: "Family", rating: 5, text: "Child support and education expenses included in maintenance order." },
  { name: "Kavya", tag: "Arbitration", rating: 5, text: "Intellectual property licensing arbitration — royalty dispute settled." },
  { name: "Ramesh", tag: "Cheque Bounce", rating: 5, text: "Timely filing within limitation period — case admitted without objections." },
  { name: "Sindhu", tag: "Consumer", rating: 5, text: "Package tour cancellation refund dispute — full amount recovered." },
  { name: "Vikram", tag: "Civil", rating: 5, text: "Suit for rendition of accounts in partnership — decree for amount due." },
  { name: "Nisha", tag: "Property", rating: 5, text: "Gift settlement deed for family property — registered without issues." },
  { name: "Arvind", tag: "Family", rating: 5, text: "Trusted advisor for matrimonial matters — honest about realistic outcomes." },
  { name: "Lakshmi", tag: "Arbitration", rating: 5, text: "Cross-border contract arbitration — coordinated with foreign counsel smoothly." },
  { name: "Gopal", tag: "Cheque Bounce", rating: 5, text: "Cheque dishonour for goods supplied — payment received after first hearing." },
  { name: "Reshma", tag: "Consumer", rating: 5, text: "Deficiency in spa membership services — refund and compensation." },
  { name: "Nagaraj", tag: "Civil", rating: 5, text: "Suit for permanent injunction and damages — both granted." },
  { name: "Chandana", tag: "Property", rating: 5, text: "Layout approval verification saved us from unauthorised site purchase." },
  { name: "Bala", tag: "Family", rating: 5, text: "Domestic violence and dowry harassment case — FIR guidance and court support." },
  { name: "Srinath", tag: "Arbitration", rating: 5, text: "Manufacturing supply arbitration — quality dispute resolved with replacement goods order." },
  { name: "Jaya", tag: "Cheque Bounce", rating: 5, text: "Professional and affordable for small business cheque bounce recovery." },
  { name: "Manjunath", tag: "Consumer", rating: 5, text: "False promise by coaching centre — fee refund with damages." },
  { name: "Shreya", tag: "Civil", rating: 5, text: "Suit for declaration of tenancy rights — protected our business premises." },
  { name: "Venkatesh", tag: "Property", rating: 5, text: "Comprehensive property due diligence report within one week." },
  { name: "Ammu", tag: "Family", rating: 5, text: "Handled my case with dignity and respect. Highly recommend Advocate Viswanathan." }
];
